name: school_life
description: An app to manage your school life.

version: 1.0.0+1

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  sqflite: any
  path: any
  intl: any
  outline_material_icons: any
  form_bloc: ^0.6.0
  flutter_form_bloc: ^0.5.0
  flutter_bloc: ^1.0.0
  dynamic_theme: ^1.0.0
  datetime_picker_formfield: ^0.4.3
  shared_preferences: ^0.5.4+1
  flutter_statusbarcolor: ^0.2.2
  flutter_colorpicker: any
  table_calendar: ^2.1.0
  device_info: ^0.4.1+3
  google_fonts: ^0.2.0
  get_it: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
