name: school_life
description: An app to manage your school life.

version: 1.0.0+1

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  sqflite: any
  path: any
  intl: any
  outline_material_icons: any
  form_bloc: ^0.6.0
  flutter_form_bloc: ^0.5.0
  flutter_bloc: ^1.0.0
  dynamic_theme: ^1.0.0
  datetime_picker_formfield: ^0.4.3
  shared_preferences: ^0.5.4+1
  flutter_statusbarcolor: ^0.2.2
  flutter_colorpicker: any
  table_calendar: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato/Lato-Regular.ttf
          weight: 400
    - family: Muli
      fonts:
        - asset: assets/fonts/Muli/Muli-Light.ttf
          weight: 300
        - asset: assets/fonts/Muli/Muli-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Muli/Muli-Bold.ttf
          weight: 700
        - asset: assets/fonts/Muli/Muli-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Muli/Muli-Black.ttf
          weight: 900
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans/OpenSans-SemiBold.ttf
          weight: 600
    - family: SourceSansPro
      fonts:
        - asset: assets/fonts/SourceSansPro/SourceSansPro-Light.ttf
          weight: 300
        - asset: assets/fonts/SourceSansPro/SourceSansPro-Regular.ttf
          weight: 400
